apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demoapp
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
    - route:
      - destination:
          host: demoapp.prod.svc.cluster.local 
        weight: 20
      - destination:
          host: demoapp.stage.svc.cluster.local
        weight: 80