FROM registry.suse.com/bci/python:latest
LABEL maintainer=glins

RUN zypper --gpg-auto-import-keys -q ref -s && zypper -q install -y python3-pip && pip install --upgrade pip
RUN zypper -n up

WORKDIR /app
COPY . /app
RUN pip --no-cache-dir install -r requirements.txt

CMD ["python3", "app.py"]
