apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
